[tool.poetry]
name = "bot-tg-16"
version = "0.1.0"
description = ""
authors = ["slivapy <faer2325@gamil.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
